name: CI/CD - Wisecow App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Login to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build & Push Docker Image
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest ./wisecow-deployment
          docker push ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest

      # Step 4: Setup kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      # Step 5: Configure Kubeconfig (you must add this as a GitHub Secret)
      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config

      # Step 6: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./wisecow-deployment/wisecow-deployment.yaml
          kubectl apply -f ./wisecow-deployment/wisecow-service.yaml
          kubectl apply -f ./wisecow-deployment/wisecow-ingress.yaml
