name: Wisecow CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t cloud344/wisecow-app:latest .
        docker push cloud344/wisecow-app:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.34.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f wisecow-deployment.yaml
        kubectl apply -f wisecow-service.yaml
